from tkinter import *
list=Tk()
list.title("TO-DO LIST")
list.geometry("400x500")
list.resizable(0,0)
list.configure(bg="wheat")

frame=Frame(list,bg="red",borderwidth=4,relief=SUNKEN)
frame.pack()
title=Label(frame,text="TO-DO LIST",bg="aqua",font="arial,20").pack()
task=Label(list, text="TASKS",bg="black",fg="red",font="arial,15").pack(fill="both")

frame2=Frame(list,bg="blue",borderwidth=6,relief=SUNKEN)
frame2.pack(pady=20)

task1=Entry(frame2,font=20,).grid(row=0,column=0)
var1=StringVar()
check1=Checkbutton(frame2, text="").grid(row=0,column=1)
task2=Entry(frame2,font=20,).grid(row=1,column=0)
var2=StringVar()
check2=Checkbutton(frame2, text="").grid(row=1,column=1)
task3=Entry(frame2,font=20,).grid(row=2,column=0)
var3=StringVar()
check3=Checkbutton(frame2, text="").grid(row=2,column=1)
task4=Entry(frame2,font=20,).grid(row=3,column=0)
var4=StringVar()
check4=Checkbutton(frame2, text="").grid(row=3,column=1)
task5=Entry(frame2,font=20,).grid(row=4,column=0)
var5=StringVar()
check5=Checkbutton(frame2, text="").grid(row=4,column=1)
task6=Entry(frame2,font=20,).grid(row=5,column=0)
var6=StringVar()
check6=Checkbutton(frame2, text="").grid(row=5,column=1)
task7=Entry(frame2,font=20,).grid(row=6,column=0)
var7=StringVar()
check7=Checkbutton(frame2, text="").grid(row=6,column=1)
task8=Entry(frame2,font=20,).grid(row=7,column=0)
var8=StringVar()
check8=Checkbutton(frame2, text="").grid(row=7,column=1)
task9=Entry(frame2,font=20,).grid(row=8,column=0)
var9=StringVar()
check9=Checkbutton(frame2, text="").grid(row=8,column=1)
task10=Entry(frame2,font=20,).grid(row=9,column=0)
var10=StringVar()
check10=Checkbutton(frame2, text="").grid(row=9,column=1)

exit=Button(frame2, text="  ALL TASK CLEAR",bg="yellow",font="arial, 20",command=list.destroy)
exit.grid()

list.mainloop()